export const endpointsMap = {
    'Apex Classes': 'ApexClasses',
    'Apex Flex Queue': 'ApexFlexQueue',
    'Approval Processes': 'ApprovalProcesses',
    'Async Apex Jobs': 'AsyncApexJobs',
    'Custom Labels': 'ExternalStrings',
    'Custom Metadata Types': 'CustomMetadata',
    'Custom Permissions': 'CustomPermissions',
    'Custom Settings': 'CustomSettings',
    'Debug Logs': 'ApexDebugLogs',
    'Dev Console': '/_ui/common/apex/debug/ApexCSIPage',
    'Flows': 'Flows',
    'Lightning App Builder': 'FlexiPageList',
    'Object Manager': 'ObjectManager',
    'Permission Set Groups': 'PermSetGroups',
    'Permission Sets': 'PermSets',
    'Platform Events': 'EventObjects',
    'Process Builder': 'ProcessAutomation',
    'Profiles': 'Profiles',
    'Public Groups': 'PublicGroups',
    'Queues': 'Queues',
    'Roles': 'Roles',
    'Scheduled Jobs': 'ScheduledJobs',
    'Setup': 'SetupOneHome',
    'Tabs': 'CustomTabs',
    'Translation Workbench Export': 'LabelWorkbenchExport',
    'Translation Workbench Import': 'LabelWorkbenchImport',
    'User Management Settings': 'UserManagementSettings',
    'Users': 'ManageUsers',
    'Workflow Rules': 'WorkflowRules'
}